//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: spdreader.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_spdreader_H__
#define __WDR_spdreader_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "spdreader_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_TEXT = 10000;
const int ID_NAME = 10001;
const int ID_NUM_OF_CALLS = 10002;
const int ID_SOURCE_LOC = 10003;
const int ID_AVG_F_TIME = 10004;
const int ID_MAX_F_TIME = 10005;
const int ID_MIN_F_TIME = 10006;
const int ID_TOTAL_F_TIME = 10007;
const int ID_AVG_FC_TIME = 10008;
const int ID_MAX_FC_TIME = 10009;
const int ID_MIN_FC_TIME = 10010;
const int ID_TOTAL_FC_TIME = 10011;
const int ID_F_PERC = 10012;
const int ID_FC_PERC = 10013;
const int ID_PARENTS_LIST = 10014;
const int ID_CHILDREN_LIST = 10015;
wxSizer *FunctionDetailPanel( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_COLUMNS = 10016;
wxSizer *ColumnsDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_STATICBITMAP = 10017;
wxSizer *AboutDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_THREADS = 10018;
const int ID_SELECT_ALL = 10019;
const int ID_DESELECT_ALL = 10020;
wxSizer *ThreadFilterDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_FIND_TEXT = 10021;
wxSizer *FindDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_LOOK_IN = 10022;
const int ID_BACK = 10023;
const int ID_UP = 10024;
const int ID_FILE_LIST = 10025;
const int ID_FILE_NAME = 10026;
const int ID_FILES_OF_TYPE = 10027;
wxSizer *RapiFileDialogFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

const int ID_MENU_FILE = 10028;
const int ID_MENU = 10029;
const int ID_IMPORT_FROM_FILE = 10030;
const int ID_FILE_RECENTFILES = 10031;
const int ID_MENU_EDIT = 10032;
const int ID_VIEW_FIND = 10033;
const int ID_VIEW_FIND_NEXT = 10034;
const int ID_MENU_VIEW = 10035;
const int ID_VIEW_FORWARD = 10036;
const int ID_VIEW_BACK = 10037;
const int ID_VIEW_FOCUS = 10038;
const int ID_VIEW_CLEAR_FOCUS = 10039;
const int ID_VIEW_THREAD_FILTER = 10040;
const int ID_VIEW_DISP_AS_PERC = 10041;
const int ID_VIEW_COLUMNS = 10042;
const int ID_VIEW_SOURCE = 10043;
const int ID_VIEW_CLOSE = 10044;
const int ID_MENU_HELP = 10045;
const int ID_HELP_DOCUMENTATION = 10046;
const int ID_HELP_ABOUT = 10047;
wxMenuBar *MainMenuFunc();

const int ID_MENU_FUNCTION_POPUP = 10048;
wxMenuBar *FunctionPopupMenu();

// Declare toolbar functions

void MainToolbarFunc( wxToolBar *parent );

// Declare bitmap functions

wxBitmap MainMenuBitmaps( size_t index );

wxBitmap NullBitmapsFunc( size_t index );

wxBitmap SPDReaderIcon( size_t index );

wxBitmap CloseButtonFunc( size_t index );

wxBitmap BackButtonFunc( size_t index );

wxBitmap UpButtonFunc( size_t index );

wxBitmap RapiFileDialogBitmapsFunc( size_t index );

wxBitmap RapiFileDialogBitmapsLgFunc( size_t index );

#endif

// End of generated file
